### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by alexander-rieder** [nickurt/laravel-plesk#1]
Hey :)
Thanks for the work you've done. Is there any documentation on the available commands / functions?

Is your plan to maintain this package in long term?

Greetings,

Alex

**Comment by nickurt** [comment]
Hi,

This package is only a "wrapper" which is using the [rest-api](https://docs.plesk.com/en-US/onyx/api-rpc/about-rest-api.79359/) of Plesk Onxy/Obsidian and is very basic (for more advanced-use, it's still beter to use the "older" [xml-api](https://github.com/nickurt/laravel-plesk-xml))

Documentation/features can be found in the [docs](https://docs.plesk.com/en-US/onyx/api-rpc/about-rest-api.79359/) of Plesk or the [SwaggerHub](https://app.swaggerhub.com/apis/plesk/api/v2) file ..

Examples [[see Api-folder](https://github.com/nickurt/laravel-plesk/tree/master/src/Api)];
```php
Plesk::client()->index();
Plesk::client()->store( array('') );

Plesk::domains()->index();
Plesk::domains()->show(1337);
```
Yes, my plan is to support/continue maintain this package, but Plesk didn't made any new features since August 2018 ...
